cargo-features = ["edition2024"]

[package]
name = "m64_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
#iced = { git = "https://github.com/iced-rs/iced.git", features = ["tokio", "highlighter", "debug"]}
tokio = {version = "1.39.2", features = ["fs"]}
bitvec = "1.0.1"
anyhow = "1.0.8"